# =============================================================================
# Marginal Analysis Module
# =============================================================================
# Displays marginal benefit analysis, net marginal tax rate, and marginal IRR

# Module UI
marginal_ui <- function(id) {
  ns <- NS(id)

  layout_columns(
    col_widths = c(12, 6, 6),

    # Top - Summary statistics
    card(
      card_header(
        class = "bg-primary text-white",
        "Marginal Analysis Summary"
      ),
      card_body(
        checkboxInput(
          ns("include_employer_marginal"),
          "Include Employer Share of Taxes",
          value = FALSE
        ),
        uiOutput(ns("summary_display"))
      )
    ),

    # Bottom left - NMTR explanation
    card(
      card_header("Net Marginal Tax Rate"),
      card_body(
        tags$p(
          "The Net Marginal Tax Rate (NMTR) shows the effective tax rate after ",
          "accounting for the present value of future benefits generated by ",
          "each dollar of earnings."
        ),
        tags$dl(
          tags$dt("NMTR = 12.4%"),
          tags$dd("No benefit accrual - pure tax (e.g., years outside top 35)"),

          tags$dt("NMTR near 0%"),
          tags$dd("Benefits roughly offset taxes (break-even)"),

          tags$dt("NMTR < 0%"),
          tags$dd("Benefits exceed taxes - effective subsidy (common for low earners)")
        ),
        tags$p(
          class = "small text-muted",
          "NMTR = (SS Tax - PV of Marginal Benefits) / Earnings"
        )
      )
    ),

    # Bottom right - Year-by-year table
    card(
      card_header("Working Years Detail"),
      card_body(
        DT::DTOutput(ns("marginal_table"))
      )
    )
  )
}

# Module Server
marginal_server <- function(id, worker_data) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns

    # Calculate marginal measures
    marginal_data <- reactive({
      data <- worker_data()
      if (is.null(data) || is.null(data$primary)) return(NULL)

      primary <- data$primary
      assumptions <- data$assumptions

      tryCatch({
        # Run marginal benefit analysis
        marginal <- marginal_benefit_analysis(primary, assumptions)

        # Run net marginal tax rate
        nmtr <- net_marginal_tax_rate(primary, assumptions,
                                       include_employer = input$include_employer_marginal)

        # Run marginal IRR
        mirr <- marginal_irr(primary, assumptions,
                             include_employer = input$include_employer_marginal)

        # Filter to working years (21-64)
        working_marginal <- marginal[marginal$age >= 21 & marginal$age <= 64, ]
        working_nmtr <- nmtr[nmtr$age >= 21 & nmtr$age <= 64, ]
        working_mirr <- mirr[mirr$age >= 21 & mirr$age <= 64, ]

        # Get unique marginal PIA rate (should be one value per worker)
        pia_rate <- unique(working_marginal$marginal_pia_rate[!is.na(working_marginal$marginal_pia_rate)])

        # Calculate summary statistics
        mean_nmtr <- mean(working_nmtr$net_marginal_tax_rate, na.rm = TRUE)
        mean_mirr_top35 <- mean(working_mirr$marginal_irr[working_mirr$in_top_35], na.rm = TRUE)
        n_top_35 <- sum(working_marginal$in_top_35, na.rm = TRUE)

        # Combine for table
        table_data <- data.frame(
          age = working_marginal$age,
          earnings = working_marginal$earnings,
          in_top_35 = working_marginal$in_top_35,
          indexed_rank = working_marginal$indexed_rank,
          delta_pv_benefits = working_marginal$delta_pv_benefits,
          net_marginal_tax_rate = working_nmtr$net_marginal_tax_rate,
          marginal_irr = working_mirr$marginal_irr
        )

        list(
          marginal_pia_rate = pia_rate[1],
          mean_nmtr = mean_nmtr,
          mean_mirr_top35 = mean_mirr_top35,
          n_top_35 = n_top_35,
          table_data = table_data
        )

      }, error = function(e) {
        NULL
      })
    })

    # Summary display
    output$summary_display <- renderUI({
      mdata <- marginal_data()
      if (is.null(mdata)) {
        return(helpText("Calculate benefits to see marginal analysis"))
      }

      # Format values
      pia_bracket <- if (!is.na(mdata$marginal_pia_rate)) {
        sprintf("%.0f%%", mdata$marginal_pia_rate * 100)
      } else "N/A"

      mean_nmtr <- if (!is.na(mdata$mean_nmtr)) {
        color <- if (mdata$mean_nmtr < 0) "text-success" else "text-warning"
        tags$span(class = color, sprintf("%.1f%%", mdata$mean_nmtr * 100))
      } else tags$span(class = "text-muted", "N/A")

      mean_mirr <- if (!is.na(mdata$mean_mirr_top35)) {
        sprintf("%.1f%%", mdata$mean_mirr_top35 * 100)
      } else "N/A"

      tags$div(
        class = "row text-center",
        tags$div(
          class = "col-3",
          tags$h6(class = "text-muted", "PIA Bracket"),
          tags$h3(pia_bracket),
          tags$p(class = "small text-muted", "Marginal rate")
        ),
        tags$div(
          class = "col-3",
          tags$h6(class = "text-muted", "Mean NMTR"),
          tags$h3(mean_nmtr),
          tags$p(class = "small text-muted", "Effective tax")
        ),
        tags$div(
          class = "col-3",
          tags$h6(class = "text-muted", "Mean Marginal IRR"),
          tags$h3(class = "text-success", mean_mirr),
          tags$p(class = "small text-muted", "Top 35 years")
        ),
        tags$div(
          class = "col-3",
          tags$h6(class = "text-muted", "Years in Top 35"),
          tags$h3(mdata$n_top_35),
          tags$p(class = "small text-muted", "Benefit-accruing")
        )
      )
    })

    # Marginal table
    output$marginal_table <- DT::renderDT({
      mdata <- marginal_data()
      if (is.null(mdata) || is.null(mdata$table_data)) return(NULL)

      df <- mdata$table_data
      df$earnings <- round(df$earnings, 0)
      df$delta_pv_benefits <- round(df$delta_pv_benefits * 100, 2)  # Convert to % per $100
      df$net_marginal_tax_rate <- round(df$net_marginal_tax_rate * 100, 1)
      df$marginal_irr <- ifelse(df$marginal_irr == -1, NA, round(df$marginal_irr * 100, 1))

      names(df) <- c("Age", "Earnings", "In Top 35", "Rank", "Delta PV (%/$100)", "NMTR (%)", "Marg IRR (%)")

      DT::datatable(
        df,
        options = list(
          pageLength = 10,
          dom = 'tp',
          scrollX = TRUE
        ),
        rownames = FALSE,
        class = "compact stripe"
      ) |>
        DT::formatCurrency("Earnings", currency = "$", digits = 0) |>
        DT::formatStyle(
          "In Top 35",
          backgroundColor = DT::styleEqual(c(TRUE, FALSE), c("#2d5a3d", "#5a2d2d"))
        )
    })

  })
}
